# .github/workflows/docker-build-push.yml

name: 'Build and Push Docker Image'

# This action has two triggers:
# 1. workflow_dispatch: Allows you to run it manually from the Actions tab.
# 2. push (tags): Runs automatically when a tag matching the pattern is pushed.
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The semantic version tag to build (e.g., 1.3.0)'
        required: true
  push:
    tags:
      # Matches tags like 1.2, 1.2.3, v1.2, v1.2.3
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

# Define an environment variable for the image name to keep it consistent
env:
  IMAGE_NAME: dandoug/budget-tracker

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        # We need to fetch all history to check the branches
        with:
          fetch-depth: 0

      - name: 'Check if tag is on main branch'
        id: check_if_on_main
        # This command checks if the tag's commit is an ancestor of the main branch.
        # It sets an output variable 'run_job' to true or false.
        run: |
          if git merge-base --is-ancestor ${{ github.ref_name }} origin/main; then
            echo "Tag is on the main branch. Proceeding."
            echo "run_job=true" >> $GITHUB_OUTPUT
          else
            echo "Tag is not on the main branch. Stopping."
            echo "run_job=false" >> $GITHUB_OUTPUT
          fi

      - name: 'Set up QEMU for multi-arch builds'
        # This step and all subsequent steps will only run if the check passed
        if: steps.check_if_on_main.outputs.run_job == 'true'
        uses: docker/setup-qemu-action@v3

      - name: 'Set up Docker Buildx'
        if: steps.check_if_on_main.outputs.run_job == 'true'
        uses: docker/setup-buildx-action@v3

      - name: 'Log in to Docker Hub'
        if: steps.check_if_on_main.outputs.run_job == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Extract Docker metadata'
        if: steps.check_if_on_main.outputs.run_job == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{inputs.version}},enable={{is_default_branch}}
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: 'Build and push Docker image'
        if: steps.check_if_on_main.outputs.run_job == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}